defmodule WaziBetWeb.Router do
  use WaziBetWeb, :router

  import WaziBetWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, html: {WaziBetWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_scope_for_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Public routes (no authentication required)
  scope "/", WaziBetWeb do
    pipe_through :browser

    # get "/", PageController, :home

    # Games are public - anyone can view games and odds
    live_session :public_games,
      on_mount: [
        {WaziBetWeb.UserAuth, :mount_current_scope},
        {WaziBetWeb.UserAuth, :mount_categories}
      ] do
      live "/", GameLive.Index, :index
      live "/games/:id", GameLive.Show, :show
    end
  end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:wazi_bet, :dev_routes) do
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: WaziBetWeb.Telemetry
      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes (generated by phx.gen.auth)

  # Routes accessible only to guests (not logged in)
  scope "/", WaziBetWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]
  
    live_session :redirect_if_user_is_authenticated,
      on_mount: [
        {WaziBetWeb.UserAuth, :redirect_if_user_is_authenticated},
        {WaziBetWeb.UserAuth, :mount_categories}
      ] do
      live "/users/register", UserLive.Registration, :new
      live "/users/log-in", UserLive.Login, :new
    end
  end

  # Routes accessible to anyone (logged in or not)
  scope "/", WaziBetWeb do
    pipe_through [:browser]

    live_session :current_user,
      on_mount: [
        {WaziBetWeb.UserAuth, :mount_current_scope},
        {WaziBetWeb.UserAuth, :mount_categories}
      ] do
      live "/users/log-in/:token", UserLive.Confirmation, :new
    end

    post "/users/log-in", UserSessionController, :create
    delete "/users/log-out", UserSessionController, :delete
  end

  # Routes requiring authentication (any logged-in user)
  scope "/", WaziBetWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :require_authenticated_user,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, :mount_categories}
      ] do
      live "/users/settings", UserLive.Settings, :edit
      live "/users/settings/confirm-email/:token", UserLive.Settings, :confirm_email
    end

    post "/users/update-password", UserSessionController, :update_password
  end

  ## Protected Application Routes (Permission-based)

  # Routes requiring 'place_bets' permission
  scope "/", WaziBetWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :place_bets,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "place-bets"}},
        {WaziBetWeb.UserAuth, :mount_categories}
      ] do
      live "/betslip", BetslipLive.Index, :index
      live "/betslip/new", BetslipLive.New, :new
    end
  end

  # Routes requiring 'view_bet_history' permission
  scope "/", WaziBetWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :view_bet_history,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "view-bet-history"}},
        {WaziBetWeb.UserAuth, :mount_categories}
      ] do
      live "/history", UserLive.History, :index
      live "/history/:id", UserLive.History, :show
    end
  end

  # Routes requiring 'view_winnings_losses' permission
  scope "/", WaziBetWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :view_winnings_losses,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "view-winnings-losses"}},
        {WaziBetWeb.UserAuth, :mount_categories}
      ] do
      live "/wallet", UserLive.Wallet, :index
    end
  end

  # Routes requiring 'cancel_bets' permission
  scope "/", WaziBetWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :cancel_bets,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "cancel-bets"}},
        {WaziBetWeb.UserAuth, :mount_categories}
      ] do
      live "/betslip/:id/cancel", BetslipLive.Cancel, :cancel
    end
  end

  ## Admin Routes (Permission-based)

  # Redirect /admin to dashboard
  scope "/admin", WaziBetWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", AdminRedirectController, :index
  end

  # Admin Dashboard - accessible to all admins
  scope "/admin", WaziBetWeb.Admin do
    pipe_through [:browser, :require_authenticated_user]

    live_session :admin_dashboard,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth,
         {:require_any_permission,
          [
            "view-users",
            "view-profits-from-losses",
            "configure-games",
            "assign-roles"
          ]}}
      ] do
      live "/dashboard", AdminLive.Dashboard, :index
    end
  end

  # Admin: View users
  scope "/admin", WaziBetWeb.Admin do
    pipe_through [:browser, :require_authenticated_user]

    live_session :admin_view_users,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "view-users"}}
      ] do
      live "/users", UserLive.Index, :index
      live "/users/:id", UserLive.Show, :show
    end
  end

  # Admin: Assign roles
  scope "/admin", WaziBetWeb.Admin do
    pipe_through [:browser, :require_authenticated_user]

    live_session :admin_assign_roles,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "assign-roles"}}
      ] do
      live "/roles", RoleLive.Index, :index
      live "/roles/assign", RoleLive.Assign, :assign
    end
  end

  # Admin: View profits
  scope "/admin", WaziBetWeb.Admin do
    pipe_through [:browser, :require_authenticated_user]

    live_session :admin_view_profits,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "view-profits-from-losses"}}
      ] do
      live "/profits", AdminLive.Profits, :index
    end
  end

  # Admin: Soft delete users
  scope "/admin", WaziBetWeb.Admin do
    pipe_through [:browser, :require_authenticated_user]

    live_session :admin_soft_delete,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "soft-delete-users"}}
      ] do
      live "/users/:id/delete", UserLive.Delete, :delete
    end
  end

  # Admin: Create users
  scope "/admin", WaziBetWeb.Admin do
    pipe_through [:browser, :require_authenticated_user]

    live_session :admin_create_users,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "create-users"}}
      ] do
      live "/users/new", UserLive.New, :new
    end
  end

  # Admin: Configure games
  scope "/admin", WaziBetWeb.Admin do
    pipe_through [:browser, :require_authenticated_user]

    live_session :admin_configure_games,
      on_mount: [
        {WaziBetWeb.UserAuth, :require_authenticated},
        {WaziBetWeb.UserAuth, {:require_permission, "configure-games"}}
      ] do
      live "/games", GameLive.Index, :index
      live "/games/new", GameLive.New, :new
      live "/games/:id", GameLive.Show, :show
    end
  end
end
